apiVersion: v1
kind: PersistentVolume
metadata:
  name: influx-volume
  labels:
    type: local
spec:
  storageClassName: influx-volume
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/influx"